__author__ = 'andrew.shvv@gmail.com'

from decimal import Decimal

MAX_DIGITS = 19
DECIMAL_PLACES = 12

OFFER_MAX_DIGITS = MAX_DIGITS + (MAX_DIGITS - DECIMAL_PLACES)
ACCOUNT_MAX_DIGITS = OFFER_MAX_DIGITS

AMOUNT_MIN_VALUE = Decimal(1 / 10 ** DECIMAL_PLACES)
PRICE_MIN_VALUE = Decimal(1 / 10 ** DECIMAL_PLACES)

POLONIEX_ORDER_MODIFIED = "orderBookModify"
POLONIEX_ORDER_REMOVED = "orderBookRemove"

CURRENCY_PAIR = "BTC_ETH"
COUNT = 20

# lower number - higher priority
PRIORITY_DELETE = 0
PRIORITY_DECREASE = 0
PRIORITY_INCREASE = 1
PRIORITY_CREATE = 1

ACTION_DELETE = 'delete'
ACTION_DECREASE = 'decrease'
ACTION_INCREASE = 'increase'
ACTION_CREATE = 'create'
