"""
Django settings for poloniexbot project.

Generated by 'django-admin startproject' using Django 1.9.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

from kombu import Queue, Exchange

from core.utils.general import load_environments, get_attr_from_module

load_environments(__name__, [
    ('SECRET_KEY', 'DJANGO_SECRET_KEY', True),
    ('POSTGRES_PASSWORD', 'POSTGRES_PASSWORD', True),
    ('WHOAMI', 'WHOAMI'),
    ('ADDRESS_POLONIEX', 'ADDRESS_POLONIEX'),
    ('ADDRESS_ABSORTIUM', 'ADDRESS_ABSORTIUM'),
    ('MODE', 'MODE'),
])

CELERY_BROKER = 'amqp://guest@docker.celery.broker//'
CELERY_RESULT_BACKEND = 'redis://docker.celery.backend'

MODE = get_attr_from_module(__name__, 'MODE')

ROUTER_URL = "http://docker.router:8080/publish"

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = MODE not in ["testnet", "realnet"]
ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django_extensions',
    'rest_framework',
    'poloniexbot',
    'poloniexbot.celery',
]

CELERY_DEFAULT_QUEUE = 'poloniexbot'
CELERY_QUEUES = (
    Queue('poloniexbot', Exchange('poloniexbot'), routing_key='poloniexbot'),
)

ETHNODE_URL = "docker.ethnode"

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'PAGE_SIZE': 10,
}

WSGI_APPLICATION = 'wsgi.application'

# Very dirty hack for forcing celery to connect to the test_postgres db while integration test.
NEED_TEST_DB = MODE in ['integration']
dbname = 'test_poloniexbot' if NEED_TEST_DB else 'poloniexbot'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': dbname,
        'USER': 'postgres',
        'PASSWORD': get_attr_from_module(__name__, 'POSTGRES_PASSWORD'),
        'HOST': 'docker.postgres',
        'PORT': '5432',
        'CONN_MAX_AGE': 500
    }
}

SILENCED_SYSTEM_CHECKS = ["models.W001"]

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True
